### ISSUE TITLE
Any way to include float parameter?

### ISSUE THREAD

**Issue by hugocroch** [helsing45/Copydeck#20]
Hello,

Do you think that your copydeck generator can include float parameters and specify the decimal number?

iOS example : %.2f = 1.23, %.1f = 1.2

We could include float like this : {{float:2}}
It would be awesome!

**Comment by helsing45** [comment]
@hugocroch if i put {{float}} what should be the IOS output

**Comment by helsing45** [comment]
Fix in the commit: 5c44b1fbb5c4d3a359fc16b18eccb76e4c65b5fa
Will be in the V0.2.3

**Comment by hugocroch** [comment]
@helsing45  Will you update the documentation?

**Comment by helsing45** [comment]
Of course i'm working on the doc before the official reals.
It's should be realse by the 26 novembre 2017
